"""empty message

Revision ID: 729225d82f1e
Revises: e63aaff5ef61
Create Date: 2017-03-12 12:19:54.456420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729225d82f1e'
down_revision = 'e63aaff5ef61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile_new',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(length=140), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile_new')
    # ### end Alembic commands ###
