"""empty message

Revision ID: 914239ba852b
Revises: 729225d82f1e
Create Date: 2017-03-12 16:30:47.007993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914239ba852b'
down_revision = '729225d82f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile_new', sa.Column('datecreated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile_new', 'datecreated')
    # ### end Alembic commands ###
